get:
  tags:
    - ApplicationMenu
  summary: Finds application menus
  description: |
    Returns application menus with pagination params and filters

    - can order on `id`, `displayName`, `applicationId`, `applicationPageId`, `menuIndex`, `parentMenuId`
    - can search on `displayName`
    - can filter on `id`, `displayName`, `applicationId`, `applicationPageId`, `menuIndex`, `parentMenuId`

  operationId: searchApplicationMenus
  parameters:
    - $ref: '../components/parameters/pageIndex.yaml'
    - $ref: '../components/parameters/pageCount.yaml'
    - $ref: '../components/parameters/pageFilter.yaml'
    - $ref: '../components/parameters/pageOrder.yaml'
    - $ref: '../components/parameters/pageSearch.yaml'
  responses:
    '200':
      description: "Success "
      headers:
        Content-Range:
          schema:
            type: integer
            format: int64
          description: The total number of matching items
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../components/schemas/ApplicationMenu.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '403':
      $ref: '../components/responses/Forbidden.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'
post:
  tags:
    - ApplicationMenu
  summary: New application menu item
  description: |
    Create an application menu item
  operationId: createApplicationMenu
  requestBody:
    description: A partial representation of an application menu in JSON
    content:
      application/json:
        schema:
          $ref: '../components/schemas/ApplicationMenuCreateRequest.yaml'
  responses:
    '200':
      description: "Success "
      content:
        application/json:
          schema:
            $ref: '../components/schemas/ApplicationMenu.yaml'
    '401':
      $ref: '../components/responses/Unauthorized.yaml'
    '403':
      $ref: '../components/responses/Forbidden.yaml'
    '400':
      $ref: '../components/responses/BadRequest.yaml'
    '5XX':
      $ref: '../components/responses/ServerError.yaml'
