# See https://redoc.ly/docs/cli/configuration/ for more information.
# https://github.com/Redocly/redoc#redoc-options-object
apis:
  main@v1:
    root: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warn
features.openapi:
  htmlTemplate: ./docs/index.html
  menuToggle: true
  noAutoAuth: true
  requiredPropsFirst: true
  pathInMiddlePanel: true
#  theme:
#    colors:
#      primary:
#        main: "#32329f"
