# See https://redoc.ly/docs/cli/configuration/ for more information.
# https://github.com/Redocly/redoc#redoc-options-object
apis:
  main@v1:
    root: ./openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warn
features.openapi:
  htmlTemplate: ./docs/index.html.hbs
  showConsole: true
  pagination: section
  menuToggle: true
  noAutoAuth: true
  requiredPropsFirst: true
  pathInMiddlePanel: true
  hideDownloadButton: true
#  theme:
#    colors:
#      primary:
#        main: "#32329f"
  generateCodeSamples:
      languages:  # Array of language config objects; indicates in which languages to generate code samples.
        - lang: curl
        - lang: Node.js
        - lang: JavaScript
        - lang: PHP
        - lang: Python
