= Bonita API

This project is about describing the Bonita web API in https://swagger.io/specification/[Open API v3] format.

This single yaml file is to become the single source of truth for the Bonita features accessible through HTTP.

Based on this file, one could generate : documentation, client in different language and/or technologie, server side stubs, ...

== Open API v3

The specification file is written in `yaml` format because multiline support is much better than in `json`
The specification has a lot of _description block_ and since it is a _documentation_, it needs to be quite verbose.

The specification file can be found here: `src/main/resources/openapi/bonita-api.yaml`

We make use of https://swagger.io/docs/specification/openapi-extensions/[extensions] to add better support for some documentation sites (x-logo, x-codeSamples, ...)

== Live Documentation

The api descriptor file can be used to render documentation sites. Those sites have different rendering and may show different parts of the specification file.
That's the reason why it is interessting to test and evaluate differents sites and rendering.

The `docker-compose.yaml` file at the project root starts two sites: a https://github.com/Redocly/redoc[ReDoc] site and a https://swagger.io/tools/swagger-ui/[swagger-ui] site.

To start the container, just issue the following comment at the project root:

[source,bash]
----
docker-compose up -d
----

You should be able to access:

- ReDoc: http://localhost:8000
- Swagger UI: http://localhost:9000

NOTE: You can keep on editing the specification file and just refresh the browser to see the changes.

== Links

*Open API documentation:*

https://swagger.io/docs/specification/basic-structure/

*IDE support:*

- intellij: https://www.jetbrains.com/help/idea/openapi.html
- eclipse: https://marketplace.eclipse.org/category/free-tagging/openapi

*Specification samples:*

- Docker API: https://docs.docker.com/engine/api/v1.40/
- Discourse API: https://docs.discourse.org/
- API hub: https://apis.guru/browse-apis/
- Samples: https://github.com/OAI/OpenAPI-Specification/tree/master/examples/v3.0