title: Application Link
description: Contains the meta information of a Bonita Living Application Link.
allOf:
  - type: object
    properties:
      link:
        description: true for an application link
        type: boolean
        enum: [ true ]
  - $ref: ./AbstractApplication.yaml
  - type: object
    description: Contains the meta information of a Bonita Living Application Link.
example:
  id: "306"
  link: "true"
  creationDate: "1411548289900"
  icon: ""
  createdBy": "1"
  profileId: "2"
  description: "My application link description"
  token: "myadvapp"
  state: "ACTIVATED"
  displayName: "My app link"
  updatedBy: "1"
  visibility: "ALL"
  editable: "true"
  lastUpdateDate: "1411548289900"
  version: "1.0"
