name: Build

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/build.yml'
      - 'docs/**'
      - 'openapi/**'
      - '.redocly.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/build.yml'
      - 'docs/**'
      - 'openapi/**'
      - '.redocly.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18

      - run: npm ci

      - run: npm run package

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: openapi.yaml
          path: dist/openapi.yaml

      - name: Get package version
        if: github.event.action != 'closed' && github.event_name == 'pull_request'
        id: package-version
        run: echo "current-version=$(cat ./package.json | jq '.version' | tr -d '"')" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: github.event.action != 'closed' && github.event_name == 'pull_request'
        with:
          name: bonita-openapi-site
          path: dist/bonita-openapi-${{ steps.package-version.outputs.current-version}}.zip
          retention-days: 5

  deployPreview:
    if: ${{ success() && github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write # surge-preview creates or updates PR comments about the deployment status
    steps:
      - uses: bonitasoft/actions/packages/surge-preview-tools@v3
        id: surge-preview-tools
        with:
          surge-token: ${{ secrets.SURGE_TOKEN_DOC }}

      - name: Download site artefact from build job
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: bonita-openapi-site
          path: ./bonita-openapi

      - name: Publish preview
        uses: afc163/surge-preview@a17bbee72e236f18b248797bbf21f1f9f06900e6 # v1.9.0
        if: steps.surge-preview-tools.outputs.can-run-surge-command == 'true'
        with:
          surge_token: ${{ secrets.SURGE_TOKEN_DOC }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: bonita-openapi
          failOnError: true
          teardown: true
          build: echo "site already built"
