name: Release
run-name: Release ${{inputs.release}} by @${{github.actor}}

on:
  workflow_dispatch:
    inputs:
      releases:
        type: choice
        description: Choose the release type to do (Following SemVer)
        options: [ patch, minor, major ]

jobs:
  release:
    permissions:
      contents: write
    name: Release pipeline
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 18

      - name: Update version
        id: newversion
        run: |
          npm version ${{github.event.inputs.releases}} --git-tag-version false
          VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          sed -i "s/version:.*/version: $VERSION/" openapi/openapi.yaml
          echo "release-tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          npm ci
          npm run package

      - name: Push tag and commit release
        run: |
          git config --global user.email "bonita-ci@bonitasoft.com"
          git config --global user.name "Bonita CI"
          git add package.json package-lock.json openapi/openapi.yaml
          git commit -m "Release ${{ steps.newversion.outputs.release-tag }}"
          git tag ${{ steps.newversion.outputs.release-tag }}
          git push origin ${{github.ref}} ${{ steps.newversion.outputs.release-tag }}

      - name: Prepare artifacts to release
        run: |
          mv dist/openapi.yaml dist/bonita-openapi-${{ steps.newversion.outputs.release-tag }}.yaml
          mv dist/postman.json dist/bonita-postman-collection-${{ steps.newversion.outputs.release-tag }}.json

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          tag: ${{ steps.newversion.outputs.release-tag }}
          name: Release ${{ steps.newversion.outputs.release-tag }}
          artifacts: dist/*

      - name: Open Bonita Java Client PR
        id: open_client_pr
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.BONITA_CI_PAT }}
          repository: bonitasoft/bonita-java-client
          event-type: new-bonita-openapi-spec-release
          client-payload: '{"spec_version": "${{steps.newversion.outputs.release-tag}}"}'
